-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 13:36:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`curso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `cursoId` INT NOT NULL AUTO_INCREMENT,
  `cursoNombre` VARCHAR(45) NULL,
  `cursoDescripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`cursoId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alumno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alumno` (
  `alumnoId` INT NOT NULL AUTO_INCREMENT,
  `alumnoNombre` VARCHAR(100) NULL,
  `alumnoApellidos` VARCHAR(200) NULL,
  `alumnoSemestre` VARCHAR(50) NULL,
  PRIMARY KEY (`alumnoId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso_alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`curso_alumno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`curso_alumno` (
  `curso_cursoId` INT NOT NULL,
  `alumno_alumnoId` INT NOT NULL,
  PRIMARY KEY (`curso_cursoId`, `alumno_alumnoId`),
  INDEX `fk_curso_has_alumno_alumno1_idx` (`alumno_alumnoId` ASC) VISIBLE,
  INDEX `fk_curso_has_alumno_curso_idx` (`curso_cursoId` ASC) VISIBLE,
  CONSTRAINT `fk_curso_has_alumno_curso`
    FOREIGN KEY (`curso_cursoId`)
    REFERENCES `mydb`.`curso` (`cursoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_has_alumno_alumno1`
    FOREIGN KEY (`alumno_alumnoId`)
    REFERENCES `mydb`.`alumno` (`alumnoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
